apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: cert-manager
      helm:
        releaseName: cert-manager
        valuesObject:
          installCRDs: true
      repoURL: https://charts.jetstack.io
      targetRevision: 1.19.2
    - chart: raw
      helm:
        releaseName: cert-manager-clusterissuer
        valuesObject:
          resources:
            - apiVersion: cert-manager.io/v1
              kind: Issuer
              metadata:
                name: localca
              spec:
                selfSigned: {}
            - apiVersion: cert-manager.io/v1
              kind: Certificate
              metadata:
                name: localca
              spec:
                isCA: true
                commonName: localca
                secretName: localca
                duration: 87600h        # 10 Jahre
                renewBefore: 720h       # 30 Tage
                privateKey:
                  algorithm: ECDSA
                  size: 256
                  encoding: PKCS8
                  rotationPolicy: Always
                issuerRef:
                  name: localca
                  kind: Issuer
            - apiVersion: cert-manager.io/v1
              kind: ClusterIssuer
              metadata:
                name: localca
              spec:
                ca:
                  secretName: localca
      repoURL: https://bedag.github.io/helm-charts/
      targetRevision: 2.0.0
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
