apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-provider-keycloak
  namespace: argocd
spec:
  destination:
    namespace: crossplane-system
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://bedag.github.io/helm-charts/
    targetRevision: 2.0.0
    chart: raw
    helm:
      valuesObject:
        resources:
          - apiVersion: v1
            kind: Secret
            metadata:
              name: keycloak-credentials
              annotations:
                argocd.argoproj.io/sync-wave: "0"
            type: Opaque
            stringData:
              client_id: "admin-cli"
              username: "admin"
              password: "admin"
              url: "https://keycloak-172-18-0-90.sslip.io"
              tls_insecure_skip_verify: "true"
          - apiVersion: pkg.crossplane.io/v1beta1
            kind: DeploymentRuntimeConfig
            metadata:
              name: provider-keycloak
              annotations:
                argocd.argoproj.io/sync-wave: "0"
            spec:
              serviceAccountTemplate:
                metadata:
                  name: provider-keycloak
          - apiVersion: pkg.crossplane.io/v1
            kind: Provider
            metadata:
              name: provider-keycloak
              annotations:
                argocd.argoproj.io/sync-wave: "1"
            spec:
              package: xpkg.upbound.io/crossplane-contrib/provider-keycloak:v2.9.0
          - apiVersion: keycloak.crossplane.io/v1beta1
            kind: ProviderConfig
            metadata:
              name: default
              annotations:
                argocd.argoproj.io/sync-wave: "2"
                argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
            spec:
              credentials:
                source: Secret
                secretRef:
                  name: keycloak-credentials
                  key: credentials
                  namespace: crossplane-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
